const {test,expect}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
const routes=['/','/cennik','/strony-dla-fizjoterapeutow','/strony-dla-gabinetow','/strony-dla-beauty','/strony-dla-warsztatow','/polityka-prywatnosci','/pliki-cookie','/szablony/barber','/szablony/fizjoterapia','/szablony/warsztat','/szablony/gabinet'];
test('pages, metadata, local links, mobile overflow and console',async({page,request})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  for(const route of routes){const res=await page.goto(route);expect(res.status(),route).toBe(200);await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('meta[name=robots]')).toHaveAttribute('content',/noindex/);await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href',/^https:\/\/znajdowalni.pl\//);const sizes=await page.evaluate(()=>({body:document.documentElement.scrollWidth,width:innerWidth}));expect(sizes.body,route).toBeLessThanOrEqual(sizes.width+1);
    const links=await page.locator('a[href]').evaluateAll(els=>els.map(el=>el.getAttribute('href')));
    for(const href of [...new Set(links)]){if(href.startsWith('#')){expect(await page.locator(href).count(),route+href).toBeGreaterThan(0);}else if(!/^(https?:|mailto:|tel:)/.test(href)){const target=new URL(href,page.url());const r=await request.get(target.pathname);expect(r.status(),route+' -> '+href).toBe(200);}}
  }expect(errors).toEqual([]);
});
test('CTA, no-link path, invalid input and recoverable network failure',async({page})=>{
  await page.goto('/');await page.locator('.hero-actions a').click();await expect(page.locator('#lead-form')).toBeVisible();await page.locator('.lead-submit').click();await expect(page.locator('#lead-source')).toBeFocused();
  await page.getByRole('button',{name:'Nie mam linku'}).click();await expect(page.locator('#business-fields')).toBeVisible();await page.getByLabel('Nazwa firmy *',{exact:true}).fill('TEST Gabinet');await page.getByLabel('Miejscowość *',{exact:true}).fill('Wrocław');await page.getByLabel('Twój e-mail *',{exact:true}).fill('błędny');await page.locator('.lead-submit').click();expect(await page.locator('#lead-email').evaluate(el=>el.validity.valid)).toBe(false);
  await page.getByLabel('Twój e-mail *',{exact:true}).fill('test@example.com');await page.getByLabel('Proszę o kontakt').check();
  await page.route('**/api/preview-request',r=>r.fulfill({status:502,contentType:'application/json',body:JSON.stringify({error:'TEST: poczta niedostępna'})}));await page.locator('.lead-submit').click();await expect(page.locator('.lead-status')).toContainText('TEST: poczta');await expect(page.getByLabel('Nazwa firmy *',{exact:true})).toHaveValue('TEST Gabinet');await expect(page.locator('.lead-submit')).toBeEnabled();
  await page.unroute('**/api/preview-request');await page.route('**/api/preview-request',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,id:'TEST-browser'})}));await page.locator('.lead-submit').click();await expect(page.locator('.lead-success')).toContainText('Mamy Twoje zgłoszenie');
});
test('successful link flow and sending state',async({page})=>{
  await page.goto('/strony-dla-beauty');await page.locator('#lead-source').fill('example.com');await page.locator('#lead-email').fill('test@example.com');await page.locator('#lead-consent').check();let release;const gate=new Promise(r=>release=r);await page.route('**/api/preview-request',async r=>{const body=r.request().postDataJSON();expect(body.source).toBe('example.com');expect(body.company).toBeUndefined();await gate;await r.fulfill({status:200,contentType:'application/json',body:'{"ok":true,"id":"TEST-link"}'});});await page.locator('.lead-submit').click();await expect(page.locator('.lead-submit')).toBeDisabled();await expect(page.locator('.lead-submit')).toHaveText('Wysyłamy…');release();await expect(page.locator('.lead-success')).toBeVisible();
});
test('preview robots, sitemap, true 404 and analytics isolation',async({page,request})=>{let ga=0;page.on('request',r=>{if(/google-analytics|googletagmanager/.test(r.url()))ga++;});await page.goto('/');await page.locator('#kontakt').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'Tylko niezbędne',exact:true}).click();await page.getByRole('button',{name:'Ustawienia cookies',exact:true}).click();await page.getByLabel('Analityka',{exact:true}).check();await page.getByRole('button',{name:'Zapisz wybór'}).click();expect(ga).toBe(0);expect(await (await request.get('/robots.txt')).text()).toContain('Disallow: /');expect(await (await request.get('/sitemap.xml')).text()).not.toContain('<loc>');expect((await request.get('/brak-takiej-strony')).status()).toBe(404);});
test('accessibility on homepage, form, pricing and industry',async({page})=>{for(const route of ['/','/cennik','/strony-dla-beauty']){await page.goto(route);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),route).toEqual([]);}});
test('mobile navigation opens, closes and moves to pricing',async({page},info)=>{if(info.project.name!=='mobile')return;await page.goto('/');await page.getByRole('button',{name:'Otwórz menu',exact:true}).click();await expect(page.locator('#mobile-nav')).toBeVisible();await page.locator('#mobile-nav').getByRole('link',{name:'Cennik',exact:true}).click();await expect(page.locator('#mobile-nav')).toBeHidden();await expect(page).toHaveURL(/#cennik/);});
