const q = (selector, scope = document) => scope.querySelector(selector);
const previewForm = (id, final = false) => `<form class="preview-form" id="${id}" novalidate>
  <div class="preview-start"><label class="sr-only" for="${id}-source">Adres obecnej strony</label><input id="${id}-source" name="source" type="url" inputmode="url" placeholder="Wklej adres obecnej strony" required><button type="button" class="button ink" data-next>Pokażcie mi moją nową stronę <span>→</span></button></div>
  <button class="text-action" type="button" data-no-site>Nie masz jeszcze strony? Wklej wizytówkę Google, profil Booksy lub informacje o firmie.</button>
  <p class="form-note">${final ? "Pierwszy podgląd jest bezpłatny. Niczego nie publikujemy bez Twojej decyzji." : "Jeden prywatny kierunek: hero, pierwsza sekcja i widok mobilny. Bez opłat."}</p><div class="form-details" hidden></div></form>`;

const fields = (noSite) => noSite ? `<div class="detail-grid"><label>Nazwa firmy<input name="company" required></label><label>Branża / czym się zajmujesz<input name="business" required></label><label>Miasto<input name="city" required></label><label>Link <small>(opcjonalnie)</small><input name="source" placeholder="Google, Facebook, Instagram..."></label></div>` : "";

function openForm(form, noSite = false) {
  const details = q('.form-details', form); const start = q('.preview-start', form);
  const source = q('[name="source"]', form)?.value || "";
  start.hidden = true; q('[name="source"]', start).disabled = true; details.hidden = false;
  details.innerHTML = `${fields(noSite)}<div class="detail-grid"><label>E-mail<input name="email" type="email" required placeholder="twoj@email.pl"></label><label>Telefon <small>(opcjonalnie)</small><input name="phone" type="tel"></label></div><label class="consent"><input name="consent" type="checkbox" required><span>Zgadzam się na kontakt w sprawie prywatnego podglądu. <a href="polityka-prywatnosci.html">Polityka prywatności</a>.</span></label><button class="button coral" type="submit">Wyślij prośbę o podgląd <span>→</span></button><button class="back" type="button" data-back>← Wróć</button>`;
  if (!noSite && source) q('[name="source"]', details).value = source;
  q('input', details)?.focus();
}

function showStatus(form, type, title, text) {
  form.innerHTML = `<div class="form-status ${type}"><span>${type === 'success' ? '✓' : '!'}</span><h3>${title}</h3><p>${text}</p></div>`;
}

async function sendPreview(data) {
  const response = await fetch(SITE.contact.endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
  const result = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(result.error || 'Nie udało się wysłać formularza.');
  return result;
}

function initForm(form) {
  form.addEventListener('click', (event) => {
    if (event.target.closest('[data-next]')) { const input = q('[name="source"]', form); if (!input.value.trim()) return input.focus(); openForm(form); }
    if (event.target.closest('[data-no-site]')) openForm(form, true);
    if (event.target.closest('[data-back]')) { q('.preview-start', form).hidden = false; q('[name="source"]', q('.preview-start', form)).disabled = false; q('.form-details', form).hidden = true; }
  });
  form.addEventListener('submit', async (event) => {
    event.preventDefault(); if (!form.reportValidity()) return;
    const button = q('[type="submit"]', form); button.disabled = true; button.textContent = 'Wysyłamy…';
    try { const result = await sendPreview(Object.fromEntries(new FormData(form))); showStatus(form, 'success', 'Dzięki. Sprawdzimy Twoją firmę i przygotujemy prywatny podgląd.', result.demo ? 'Formularz działa obecnie w trybie demonstracyjnym. Dane nie zostały jeszcze przekazane. Skonfigurujemy wysyłkę przed publikacją.' : 'Odezwemy się na podany e-mail. To nie jest automatyczna publikacja. To tylko pierwszy krok.'); }
    catch (error) { showStatus(form, 'demo', 'Formularz jest gotowy, ale działa jeszcze w trybie demonstracyjnym.', 'Nie wysłaliśmy Twoich danych, ponieważ produkcyjna wysyłka nie została jeszcze skonfigurowana. Napisz na ' + SITE.contact.email + '.'); }
  });
}

function init() {
  q('#top').innerHTML = `<div class="nav wrap"><a class="brand-lockup" href="#top" aria-label="Znajdowalni — strona główna"><img src="assets/brand/znajdowalni-kadr-final.svg" alt="Znajdowalni"></a><nav>${SITE.nav.map(([name, href]) => `<a href="${href}">${name}</a>`).join('')}</nav><button class="nav-cta" data-scroll-preview>Zobacz preview <span>↘</span></button></div>`;
  q('#main').innerHTML = `<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><p class="eyebrow">STRONY DLA LOKALNYCH FIRM</p><h1>Daj się znaleźć<br><em>klientom.</em></h1><p class="lede">Wklej swoją wizytówkę Google, Booksy albo obecną stronę. Pokażemy Ci bezpłatnie, jak mogłaby wyglądać nowa strona Twojej firmy.</p>${previewForm('hero-preview')}</div><div class="hero-art" aria-hidden="true"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="signal-card card-one"><b>Twoja firma</b><small>jest dokładnie tam, gdzie trzeba</small></div><div class="signal-card card-two"><span>Nowy klient</span><strong>„O, jest!”</strong></div><div class="spark s1">✦</div><div class="spark s2">✳</div></div></div></section>
  <section class="benefits"><div class="wrap benefit-grid">${SITE.benefits.map((item, i) => `<article><span>0${i + 1}</span><h2>${item[0]}</h2><p>${item[1]}</p></article>`).join('')}</div></section>
  <section class="section scenarios" id="dla-kogo"><div class="wrap"><p class="eyebrow">DLA KOGO</p><h2>Nie potrzebujesz kolejnego<br><em>projektu do pilnowania.</em></h2><div class="scenario-grid"><article><p class="kicker">START OD ZERA</p><h3>Nie masz jeszcze strony</h3><p>Masz Google, Booksy, social media albo klientów z polecenia. Zbudujemy stronę na podstawie informacji, które już istnieją.</p></article><article><p class="kicker">NOWY ROZDZIAŁ</p><h3>Masz stronę, ale wolałbyś jej nie pokazywać</h3><p>Odświeżymy wygląd, strukturę, mobile, kontakt i sposób prezentowania usług.</p></article></div></div></section>
  <section class="section process" id="jak-to-dziala"><div class="wrap"><div class="section-heading"><div><p class="eyebrow">JAK TO DZIAŁA</p><h2>Bez wielogodzinnych warsztatów.<br><em>Bez technicznego chaosu.</em></h2></div><p>Trzy kroki. Najpierw widzisz efekt, potem decydujesz.</p></div><div class="steps">${[["Daj nam namiar", "Wklejasz stronę, Google, Booksy, social media albo kilka informacji o firmie."], ["Oglądasz projekt", "Dostajesz prywatny link z propozycją nowej strony."], ["Decydujesz", "Podoba Ci się? Dopracowujemy i publikujemy. Nie? Za pierwszy preview nie płacisz."]].map((step, i) => `<article><span>0${i+1}</span><h3>${step[0]}</h3><p>${step[1]}</p></article>`).join('')}</div></div></section>
  <section class="section case-study" id="realizacje"><div class="wrap case-grid"><div class="case-copy"><p class="eyebrow">PRZYKŁADOWA REALIZACJA</p><h2>Pani Terapia.<br><em>Spokojna strona, jasny pierwszy krok.</em></h2><p>Gabinet, oferta, kontakt i rezerwacja zebrane w jednym miejscu. Bez wyszukiwania informacji po kilku profilach.</p><p class="case-note">Przykład pokazuje kierunek dla gabinetu terapeutycznego.</p></div><div class="case-visual"><img src="assets/pani-terapia-case.png" alt="Widok przykładowej strony Pani Terapia"></div></div></section>
  <section class="section directions"><div class="wrap"><p class="eyebrow">PRZYKŁADOWE KIERUNKI</p><h2>Zobacz, co możemy stworzyć<br><em>dla Twojej branży.</em></h2><p class="intro">Trzy przykładowe kierunki, które pokazują, jak różnie może działać prosta strona lokalnej firmy.</p><div class="direction-grid">${SITE.industries.map(item => `<article class="site-preview ${item.tone}"><div class="browser"><i></i><i></i><i></i></div><div class="mini-nav">${item.name}<span>Menu</span></div><h3>${item.title}</h3><div class="mini-lines"><b></b><b></b><b></b></div><button>Umów termin →</button><p>${item.tag}</p></article>`).join('')}</div></div></section>
  <section class="section pricing" id="cennik"><div class="wrap"><p class="eyebrow">PROSTY CENNIK</p><h2>Strona, którą masz z głowy.<br><em>Od 299 zł miesięcznie.</em></h2><p class="intro">Najpierw zobacz prywatny podgląd. Potem wybierasz pakiet, który pasuje do Twojego tempa pracy.</p><div class="plans">${SITE.plans.map(plan => `<article class="plan"><h3>${plan.name}</h3><p>${plan.lead}</p><div class="price"><strong>${plan.price}</strong><span>zł netto<br>/ miesiąc</span></div><a class="button light" href="#preview">Najpierw zobacz swoją stronę <span>→</span></a><ul>${plan.features.map(feature => `<li>${feature}</li>`).join('')}</ul></article>`).join('')}</div><div class="onboarding"><div><p class="eyebrow">PRZEJRZYŚCIE</p><h3>Przygotowanie i uruchomienie strony</h3></div><div class="old-price">3000 zł <small>netto</small></div><div class="arrow">→</div><div class="new-price">0 zł <small>przy umowie na minimum 12 miesięcy</small></div><p>Bez zobowiązania na 12 miesięcy: 3000 zł netto za wdrożenie + wybrany abonament.</p></div></div></section>
  <section class="section included"><div class="wrap"><p class="eyebrow">W KAŻDYM ABONAMENCIE</p><div class="included-grid">${["Projekt i publikacja", "Hosting, SSL i bezpieczeństwo", "Strona wygodna na telefonie", "Formularz, telefon i mapa", "Podpięcie istniejących rezerwacji", "Techniczne podstawy SEO", "Google Search Console", "Zmiany zamiast rozliczania minut"].map(item => `<div><span>✦</span>${item}</div>`).join('')}</div></div></section>
  <section class="section compare"><div class="wrap"><p class="eyebrow">UCZCIWIE</p><h2>Nie każda firma<br><em>potrzebuje agencji.</em></h2><div class="compare-grid"><article class="ours"><h3>Znajdowalni</h3><b>Dobre, gdy</b><p>Chcesz szybko dostać profesjonalną stronę lokalnej firmy bez zajmowania się technologią.</p><b>Ograniczenia</b><p>Nie budujemy sklepów, aplikacji ani wielkich customowych platform.</p></article><article><h3>Agencja</h3><b>Dobra, gdy</b><p>Potrzebujesz dużego serwisu, custom UX, warsztatów, wielu integracji i masz większy budżet.</p></article><article><h3>DIY / builder / WordPress</h3><b>Dobry, gdy</b><p>Chcesz wszystko robić sam i masz na to czas.</p></article></div></div></section>
  <section class="section faq" id="faq"><div class="wrap faq-grid"><div><p class="eyebrow">FAQ</p><h2>Masz pytanie?<br><em>To normalne.</em></h2><p>Jeśli nie ma go tutaj, napisz przy prośbie o preview.</p></div><div class="accordions">${SITE.faq.map(item => `<details><summary>${item[0]}<span>+</span></summary><p>${item[1]}</p></details>`).join('')}</div></div></section>
  <section class="final-cta" id="preview"><div class="wrap"><p class="eyebrow">PIERWSZY KROK JEST PROSTY</p><h2>Zobaczmy, jak może wyglądać<br><em>Twoja firma online.</em></h2>${previewForm('final-preview', true)}</div></section>`;
  q('#footer').innerHTML = `<div class="wrap footer-inner"><a class="brand-lockup" href="#top"><img src="assets/brand/znajdowalni-kadr-final.svg" alt="Znajdowalni"></a><p>Daj się znaleźć klientom.</p><div><a href="polityka-prywatnosci.html">Polityka prywatności</a> · <a href="pliki-cookie.html">Pliki cookie</a></div><small>© ${new Date().getFullYear()} Znajdowalni</small></div>`;
  q('.scenarios').insertAdjacentHTML('afterend', `<section class="industry-fit"><div class="wrap fit-layout"><div><p class="eyebrow">DLA KOGO</p><h2>Małe i średnie<br><em>firmy usługowe.</em></h2></div><div><div class="industry-tags">${['gabinet i klinika','psycholog i terapeuta','beauty i wellness','fryzjer i barber','dentysta i ortodonta','fizjoterapia','warsztat i serwis','usługi domowe','remonty i wykończenia','architekt wnętrz','prawo i księgowość','biuro nieruchomości','fotograf i filmowiec','szkoła językowa','trener i studio ruchu','weterynarz','catering i eventy'].map(name => `<span>${name}</span>`).join('')}</div><p class="industry-note">Standard sprawdza się najlepiej dla jednej lokalnej firmy usługowej. Większą liczbę lokalizacji, podstron lub integracji ustalamy indywidualnie.</p></div></div></section>`);
  q('.hero .lede').textContent = 'Masz obecną stronę? Wklej jej adres, a pokażemy Ci bezpłatnie, jak mogłaby wyglądać nowa strona Twojej firmy.';
  q('.hero .lede').textContent = 'Klient trafia na Ciebie w Google, Booksy albo z polecenia. Daj mu jedno miejsce, w którym szybko zrozumie ofertę, zaufa i zrobi następny krok.';
  q('.benefits').insertAdjacentHTML('afterend', `<section class="positioning"><div class="wrap positioning-grid"><p class="eyebrow">NIE STRONA DLA STRONY</p><h2>Twoja firma działa dobrze.<br><em>Niech dobrze wygląda online.</em></h2><p>Nie budujemy kolejnej strony do odhaczenia. Porządkujemy miejsce, do którego trafia klient: ofertę, kontakt, lokalizację i rezerwację. Tak, żeby łatwiej było wybrać właśnie Ciebie.</p></div></section>`);
  q('.scenarios h2').innerHTML = 'Nie chodzi o nową stronę.<br><em>Chodzi o dobre pierwsze wrażenie.</em>';
  q('.process h2').innerHTML = 'Ty prowadzisz firmę.<br><em>My zajmujemy się stroną.</em>';
  q('.process .section-heading > p').textContent = 'Bez technicznego języka, bez gonienia wykonawcy i bez zastanawiania się, co jest do zrobienia.';
  q('.pricing h2').innerHTML = 'Strona? Masz ją z głowy.<br><em>Ty po prostu prowadzisz firmę.</em>';
  q('.pricing .intro').textContent = 'My ją tworzymy, publikujemy i później ogarniamy. Dobra obecność online pomaga klientom znaleźć ofertę, zaufać Twojej firmie i łatwo zrobić następny krok.';
  q('.old-price').innerHTML = '2499 zł <small>netto</small>';
  q('.new-price').innerHTML = '0 zł <small>przy umowie na minimum 12 miesięcy</small>';
  q('.onboarding > p').textContent = 'Wolisz bez rocznego zobowiązania? Płacisz 2499 zł netto za przygotowanie strony i korzystasz z abonamentu z miesięcznym okresem wypowiedzenia.';
  q('.pricing').insertAdjacentHTML('afterend', `<section class="choose-plan"><div class="wrap"><p class="eyebrow">CO WYBRAĆ?</p><div class="choose-grid"><article><h2>Standard będzie dla Ciebie, jeśli</h2><p>Chcesz mieć stronę z głowy. Gdy coś trzeba zmienić, po prostu piszesz do nas.</p></article><article><h2>Pro będzie dla Ciebie, jeśli</h2><p>Chcesz samodzielnie publikować treści, prowadzić blog albo częściej aktualizujesz ofertę.</p></article></div><div class="integration-note"><h3>Masz już system rezerwacji? Super.</h3><p>Booksy, ZnanyLekarz, Calendly lub inny system podpinamy do strony w ramach abonamentu. Konfiguracja nowego systemu od zera jest usługą dodatkową. Abonamenty zewnętrznych usług rozliczasz bezpośrednio z ich dostawcą.</p></div></div></section>`);
  q('.included .eyebrow').textContent = 'CO POMAGA KLIENTOWI WYBRAĆ CIEBIE';
  q('.accordions').insertAdjacentHTML('afterbegin', `<details><summary>Czy strona będzie zoptymalizowana pod Google i wyszukiwanie AI?<span>+</span></summary><p>Każdą stronę budujemy zgodnie z dobrymi praktykami SEO. Porządkujemy ją tak, żeby Google i asystenci AI mogli ją odczytać i zrozumieć. Przed publikacją sprawdzamy najważniejsze elementy techniczne.</p><p>Nie obiecujemy konkretnej pozycji w Google ani cytowania przez AI. Widoczność nowej strony zależy także od reputacji budowanej w czasie, opinii, wizytówki Google i linków z innych stron. Dostajesz stronę zbudowaną poprawnie, a nie obietnicę wyniku.</p></details>`);
  [...document.querySelectorAll('.accordions details')].find(item => item.querySelector('summary')?.textContent.includes('Czy zapewniacie pozycjonowanie'))?.remove();
  q('.accordions').insertAdjacentHTML('afterbegin', `<details><summary>Czy naprawdę mogę zacząć za 0 zł?<span>+</span></summary><p>Tak. Przy umowie na minimum 12 miesięcy otrzymujesz 100% rabatu na przygotowanie i uruchomienie strony, standardowo wycenione na 2499 zł netto.</p></details><details><summary>Czy muszę podpisywać umowę na rok?<span>+</span></summary><p>Nie. Możesz zapłacić 2499 zł netto za uruchomienie i korzystać z abonamentu z miesięcznym okresem wypowiedzenia.</p></details><details><summary>Co dzieje się po 12 miesiącach?<span>+</span></summary><p>Abonament działa dalej na czas nieokreślony z miesięcznym okresem wypowiedzenia.</p></details><details><summary>Czy Booksy lub ZnanyLekarz kosztują dodatkowo?<span>+</span></summary><p>Podpięcie istniejącego systemu jest w cenie. Opłaty pobierane przez Booksy, ZnanyLekarz, Calendly lub inne zewnętrzne usługi rozliczasz bezpośrednio z ich dostawcą.</p></details>`);
  [...document.querySelectorAll('.accordions details')].filter(item => ['Co dzieje się po 12 miesiącach?', 'Czy podłączacie Booksy, Calendly, ZnanyLekarz i płatności?'].includes(item.querySelector('summary')?.textContent.replace('+', '').trim())).slice(1).forEach(item => item.remove());
  [...document.querySelectorAll('.accordions details')].find(item => item.querySelector('summary')?.textContent.includes('Czy podłączacie Booksy, Calendly'))?.remove();
  q('.steps article:nth-child(3) p').textContent = 'Podoba Ci się kierunek? Działamy dalej. Chcesz coś zmienić? Mówisz, co nie gra, a my dopasowujemy projekt do Twoich potrzeb. Za preview strony nie płacisz.';
  document.querySelectorAll('.preview-form').forEach(initForm);
  document.querySelectorAll('[data-scroll-preview]').forEach(button => button.addEventListener('click', () => q('#hero-preview').scrollIntoView({ behavior: 'smooth', block: 'center' })));
}
document.addEventListener('DOMContentLoaded', init);
