/* Centralne dane marketingowe — gotowe do wykorzystania przez przyszłe landing pages branżowe. */
const SITE = {
  contact: { email: "travoltautomation@gmail.com", endpoint: "/api/preview-request" },
  nav: [["Dla kogo", "#dla-kogo"], ["Jak to działa", "#jak-to-dziala"], ["Cennik", "#cennik"], ["FAQ", "#faq"]],
  benefits: [["Zrobione za Ciebie", "Nie uczysz się WordPressa ani buildera. Przygotowujemy, publikujemy i utrzymujemy stronę."], ["Na telefonie ma działać najlepiej", "Oferta, telefon, lokalizacja i rezerwacja muszą być oczywiste również na małym ekranie."], ["Najpierw zobacz", "Najpierw dostajesz prywatny podgląd. Dopiero później decydujesz."]],
  industries: [{ name:"Beauty", tone:"beauty", title:"Studio, do którego chce się umówić.", tag:"Booksy · cennik · rezerwacja" }, { name:"Fizjoterapia", tone:"physio", title:"Spokojnie. Konkretnie. Blisko.", tag:"usługi · zaufanie · kontakt" }, { name:"Warsztat", tone:"garage", title:"Serwis bez szukania numeru.", tag:"telefon · mapa · termin" }],
  plans: [{ name:"Znajdowalni Standard", price:"349", lead:"Dla firmy, która chce mieć stronę i nie chce się nią zajmować.", features:["kompletna strona firmy", "hosting, SSL i wersja mobile", "formularz kontaktowy, mapa i kontakt telefoniczny", "techniczne podstawy SEO i Google Search Console", "podpięcie istniejącego systemu rezerwacji", "utrzymanie techniczne i monitoring", "5 zgłoszeń zmian miesięcznie"] }, { name:"Znajdowalni Pro", price:"599", lead:"Dla firmy, która częściej aktualizuje stronę albo chce część treści prowadzić samodzielnie.", features:["wszystko ze Standard", "CMS do własnej edycji treści", "blog lub aktualności", "samodzielna edycja usług, cen, FAQ i wybranych sekcji", "10 zgłoszeń zmian miesięcznie", "priorytetowa obsługa"] }],
  addOns: ["Konfiguracja Calendly", "Konfiguracja systemu rezerwacji", "Konfiguracja płatności online", "Dodatkowa podstrona", "Dodatkowy landing page", "Dodatkowy język", "CMS jako dodatek do Standard", "Konfiguracja CMS", "Szkolenie z CMS", "Rozbudowany formularz", "Dodatkowe integracje", "Dodatkowa sekcja", "Stand NFC / QR do opinii Google"],
  faq: [["Czy podgląd naprawdę jest bezpłatny?", "Tak. Bez opłat przygotowujemy jeden prywatny kierunek: hero, pierwszą sekcję i widok mobilny. Nic nie jest publikowane, zanim nie podejmiesz decyzji."], ["Co mam wysłać, jeśli nie mam strony?", "Wizytówkę Google, profil Booksy, Facebook, Instagram albo po prostu nazwę firmy, branżę i miasto. To wystarczy na start."], ["Czy muszę przenosić domenę?", "Nie. Najpierw oglądasz podgląd. Do domeny wracamy dopiero po decyzji o publikacji."], ["Do kogo należy domena?", "Domena i Twoje konta Google, Booksy, Calendly oraz inne zewnętrzne systemy pozostają Twoje."], ["Co dzieje się po 12 miesiącach?", "TODO: uzupełnij zasady kontynuacji współpracy, rozliczeń i ewentualnego wydania strony zgodnie z zatwierdzonym regulaminem."], ["Co jeśli chcę zrezygnować wcześniej?", "TODO: uzupełnij zasady wcześniejszego zakończenia umowy po potwierdzeniu ich w regulaminie."], ["Co dokładnie oznacza „drobna zmiana”?", "To na przykład zmiana ceny, tekstu, zdjęcia, godzin otwarcia, telefonu, adresu, linku lub CTA. Nowa podstrona, duża sekcja, redesign, funkcja, sklep czy nowa integracja wykraczają poza ten zakres."], ["Ile trwa wykonanie zmian?", "Drobne zmiany realizujemy standardowo w 2 do 5 dni roboczych. W Pro są obsługiwane priorytetowo."], ["Czy mogę sam edytować stronę? Co daje CMS?", "Tak, w pakiecie Pro możesz samodzielnie edytować wybrane treści, na przykład usługi, ceny lub ustalone sekcje."], ["Czy podłączacie Booksy, Calendly, ZnanyLekarz i płatności?", "Podpinamy istniejące systemy rezerwacji. Możemy też podłączyć istniejący system płatności; nie budujemy własnych systemów rezerwacji ani płatności."], ["Czy zapewniacie pozycjonowanie?", "Wdrażamy techniczne podstawy SEO i stronę przygotowaną tak, aby Google mogło ją poprawnie zrozumieć. Nie obiecujemy konkretnej pozycji w wynikach."], ["Czy robicie sklepy internetowe?", "Nie. Znajdowalni są dla prostych, profesjonalnych stron lokalnych firm usługowych. Sklepy, aplikacje i duże platformy to obszar dla innego modelu współpracy."], ["Czy można później dodać podstrony?", "Tak. Rozbudowę ustalamy i wyceniamy osobno, zanim zaczniemy pracę."]]
};

/* Podstrona oferty używa tego samego źródła prawdy co strona główna. */
setTimeout(() => {
  if (!document.querySelector('link[href="palette.css"]')) document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="palette.css">');
  const oldPrice = document.querySelector('.old-price');
  const onboardingNote = document.querySelector('.onboarding > p');
  if (oldPrice) oldPrice.innerHTML = '2499 zł <small>netto</small>';
  if (onboardingNote) onboardingNote.textContent = 'Wolisz bez rocznego zobowiązania? Płacisz 2499 zł netto za przygotowanie strony i korzystasz z abonamentu z miesięcznym okresem wypowiedzenia.';
}, 0);
