/* Centralne dane marketingowe — gotowe do wykorzystania przez przyszłe landing pages branżowe. */
const SITE = {
  contact: { email: "travoltautomation@gmail.com", endpoint: "/api/preview-request" },
  nav: [["Dla kogo", "#dla-kogo"], ["Jak to działa", "#jak-to-dziala"], ["Cennik", "#cennik"], ["FAQ", "#faq"]],
  benefits: [["Klient nie czeka", "Szybka, przejrzysta strona pomaga klientowi zostać, zadzwonić i wybrać właśnie Ciebie."], ["Działa tam, gdzie szuka klient", "Świetny wygląd i wygodna obsługa na telefonie, z którego korzysta większość Twoich klientów."], ["Kontakt jest prosty", "Telefon, mapa, formularz i rezerwacja są pod ręką, także na małym ekranie."]],
  industries: [{ name:"Beauty", tone:"beauty", title:"Studio, do którego chce się umówić.", tag:"Booksy · cennik · rezerwacja" }, { name:"Fizjoterapia", tone:"physio", title:"Spokojnie. Konkretnie. Blisko.", tag:"usługi · zaufanie · kontakt" }, { name:"Warsztat", tone:"garage", title:"Serwis bez szukania numeru.", tag:"telefon · mapa · termin" }],
  plans: [{ name:"Znajdowalni Standard", price:"349", lead:"Dla właściciela firmy, który chce mieć stronę z głowy.", features:["Kompletna strona gotowa do publikacji", "Klient łatwo zadzwoni lub zarezerwuje także z telefonu", "Formularz, mapa i łatwy kontakt", "Strona gotowa na wyszukiwanie w Google", "Podpięcie Twoich rezerwacji", { title:"Możliwość dodania opinii klientów z Google", note:"Jeśli masz wizytówkę Google, możemy pokazać wybrane opinie na stronie." }, { title:"Hosting, certyfikat SSL i opieka techniczna", note:"SSL chroni dane przesyłane przez stronę." }, "5 zgłoszeń zmian miesięcznie"] }, { name:"Znajdowalni Pro", price:"599", lead:"Dla właściciela firmy, który częściej aktualizuje ofertę.", features:["Wszystko ze Standard", "Samodzielnie zmieniasz wybrane usługi, ceny, FAQ i treści", "Publikujesz aktualności, wpisy blogowe i rozwijasz ofertę", "Krótki raport z Google Analytics raz na 3 miesiące", "10 zgłoszeń zmian miesięcznie", "Priorytetowa obsługa"] }],
  addOns: ["Konfiguracja Calendly", "Konfiguracja systemu rezerwacji", "Konfiguracja płatności online", "Dodatkowa podstrona", "Dodatkowy landing page", "Dodatkowy język", "CMS jako dodatek do Standard", "Konfiguracja CMS", "Szkolenie z CMS", "Rozbudowany formularz", "Dodatkowe integracje", "Dodatkowa sekcja", "Stand NFC / QR do opinii Google"],
  faq: [["Czy podgląd naprawdę jest bezpłatny?", "Tak. Bez opłat przygotowujemy jeden prywatny kierunek: hero, pierwszą sekcję i widok mobilny. Nic nie jest publikowane, zanim nie podejmiesz decyzji."], ["Co mam wysłać, jeśli nie mam strony?", "Wizytówkę Google, profil Booksy, Facebook, Instagram albo po prostu nazwę firmy, branżę i miasto. To wystarczy na start."], ["Czy muszę przenosić domenę?", "Nie. Najpierw oglądasz podgląd. Do domeny wracamy dopiero po decyzji o publikacji."], ["Do kogo należy domena?", "Domena i Twoje konta Google, Booksy, Calendly oraz inne zewnętrzne systemy pozostają Twoje."], ["Co dzieje się po 12 miesiącach?", "TODO: uzupełnij zasady kontynuacji współpracy, rozliczeń i ewentualnego wydania strony zgodnie z zatwierdzonym regulaminem."], ["Co jeśli chcę zrezygnować wcześniej?", "TODO: uzupełnij zasady wcześniejszego zakończenia umowy po potwierdzeniu ich w regulaminie."], ["Co dokładnie oznacza „drobna zmiana”?", "To na przykład zmiana ceny, tekstu, zdjęcia, godzin otwarcia, telefonu, adresu, linku lub CTA. Nowa podstrona, duża sekcja, redesign, funkcja, sklep czy nowa integracja wykraczają poza ten zakres."], ["Ile trwa wykonanie zmian?", "Drobne zmiany realizujemy standardowo w 2 do 5 dni roboczych. W Pro są obsługiwane priorytetowo."], ["Czy mogę sam edytować stronę? Co daje CMS?", "Tak, w pakiecie Pro możesz samodzielnie edytować wybrane treści, na przykład usługi, ceny lub ustalone sekcje."], ["Czy podłączacie Booksy, Calendly, ZnanyLekarz i płatności?", "Podpinamy istniejące systemy rezerwacji. Możemy też podłączyć istniejący system płatności; nie budujemy własnych systemów rezerwacji ani płatności."], ["Czy strona będzie widoczna w Google?", "Budujemy stronę tak, aby Google mogło poprawnie odczytać jej ofertę, lokalizację i najważniejsze informacje. Nie obiecujemy konkretnej pozycji w wynikach."], ["Czy robicie sklepy internetowe?", "Nie. Znajdowalni są dla prostych, profesjonalnych stron lokalnych firm usługowych. Sklepy, aplikacje i duże platformy to obszar dla innego modelu współpracy."], ["Czy można później dodać podstrony?", "Tak. Rozbudowę ustalamy i wyceniamy osobno, zanim zaczniemy pracę."]]
};

/* Podstrona oferty używa tego samego źródła prawdy co strona główna. */
setTimeout(() => {
  if (!document.querySelector('link[href="palette.css"]')) document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="palette.css">');
  const oldPrice = document.querySelector('.old-price');
  const onboardingNote = document.querySelector('.onboarding > p');
  if (oldPrice) oldPrice.innerHTML = '2499 zł <small>netto</small>';
  if (onboardingNote) onboardingNote.textContent = 'Wolisz bez rocznego zobowiązania? Płacisz 2499 zł netto za przygotowanie strony i korzystasz z abonamentu z miesięcznym okresem wypowiedzenia.';
}, 0);
