const {test}=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {validate,record,message}=require('../lib/lead');
const {createHandler}=require('../api/preview-request');
const valid=()=>({email:'owner@example.com',source:'example.com',consent:'on',startedAt:Date.now()-3000,requestId:randomUUID()});
function response(){return {code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(c){this.code=c;return this;},json(data){this.body=data;return this;}};}
function request(body,extra={}){return {method:'POST',body,headers:{'content-type':'application/json',host:'localhost',origin:'http://localhost','x-real-ip':randomUUID()},...extra};}
test('link alone identifies company; no repeated brief required',()=>{const {data,error}=validate(valid());assert.ifError(error);assert.equal(data.source,'https://example.com/');});
test('no-link flow requires company and city',()=>{assert.ok(validate({...valid(),source:''}).error);assert.ok(validate({...valid(),source:'',company:'Firma',city:'Wrocław'}).data);});
test('reject invalid email, consent, types, oversized text and invalid URLs',()=>{for(const patch of [{email:'wrong'},{email:'x@example.com\r\nBcc:a@example.com'},{consent:'false'},{email:['a@b.pl']},{source:'javascript:alert(1)'},{message:'a'.repeat(3001)},{startedAt:Date.now()}])assert.ok(validate({...valid(),...patch}).error,JSON.stringify(patch).slice(0,80));});
test('mail escapes submitted content and carries audit record',()=>{const lead=record(validate({...valid(),company:'<script>bad</script>'}).data,true);const mail=message(lead);assert.ok(mail.title.startsWith('[TEST]'));assert.ok(!mail.html.includes('<script>'));assert.equal(lead.consent.contact,true);assert.equal(lead.research.facts.length,0);});
test('unconfigured delivery returns controlled error, never false success',async()=>{const res=response();await createHandler(async()=>{const e=new Error();e.code='CONFIG';throw e;})(request(valid()),res);assert.equal(res.code,503);assert.equal(res.body.ok,undefined);});
test('success only after delivery; repeated ID does not send twice',async()=>{let sends=0;const handler=createHandler(async()=>{sends++;});const body=valid();for(let i=0;i<2;i++){const res=response();await handler(request(body),res);assert.equal(res.code,200);assert.equal(res.body.id,body.requestId);}assert.equal(sends,1);});
test('reject spam, cross-origin, GET and oversized request before delivery',async()=>{let sends=0;const handler=createHandler(async()=>{sends++;});for(const [req,code]of [[request({...valid(),website:'bot'}),400],[request(valid(),{method:'GET'}),405],[request(valid(),{headers:{'content-type':'application/json',host:'site.com',origin:'https://evil.com'}}),403],[request({...valid(),message:'a'.repeat(13000)}),413]]){const res=response();await handler(req,res);assert.equal(res.code,code);}assert.equal(sends,0);});
test('mail provider failure preserves retry and never records success',async()=>{const res=response();await createHandler(async()=>{throw new Error('SMTP failure');})(request(valid()),res);assert.equal(res.code,502);});
test('rate limits repeated attempts',async()=>{const handler=createHandler(async()=>{});const ip=randomUUID();for(let i=0;i<9;i++){const req=request(valid());req.headers['x-real-ip']=ip;const res=response();await handler(req,res);assert.equal(res.code,i<8?200:429);}});
